<?php
// auto-generated by sfPropelAdmin
// date: 2018/02/13 14:32:10
?>
<ul class="sf_admin_actions">
    <li><?php echo button_to(__(' delete'), 'kader/_delete?id='.$kader->getId(), array (
  'class' => 'sf_admin_action__delete',
)) ?></li>
</ul>
