<?php
// auto-generated by sfPropelAdmin
// date: 2018/02/07 04:47:13
?>
<td colspan="11">
    <?php echo $kader->getNama() ?>
     - 
    <?php echo $kader->getAlamat() ?>
     - 
    <?php echo $kader->getJenisKader() ?>
     - 
    <?php echo $kader->getWilayah() ?>
     - 
    <?php echo $kader->getRt() ?>
     - 
    <?php echo $kader->getRw() ?>
     - 
    <?php echo $kader->getNoTelp() ?>
     - 
    <?php echo get_partial('valid_view', array('type' => 'list', 'kader' => $kader)) ?>
     - 
    <?php echo get_partial('status_view', array('type' => 'list', 'kader' => $kader)) ?>
     - 
    <?php echo $kader->getKeterangan() ?>
     - 
    <?php echo get_partial('opsi', array('type' => 'list', 'kader' => $kader)) ?>
     - 
</td>