<?php
// auto-generated by sfPropelAdmin
// date: 2018/02/06 04:14:56
?>
<td colspan="9">
    <?php echo $kader->getNama() ?>
     - 
    <?php echo $kader->getAlamat() ?>
     - 
    <?php echo $kader->getJenisKader() ?>
     - 
    <?php echo $kader->getWilayah() ?>
     - 
    <?php echo $kader->getRt() ?>
     - 
    <?php echo $kader->getRw() ?>
     - 
    <?php echo $kader->getNoTelp() ?>
     - 
    <?php echo get_partial('valid', array('type' => 'list', 'kader' => $kader)) ?>
     - 
    <?php echo get_partial('opsi', array('type' => 'list', 'kader' => $kader)) ?>
     - 
</td>