<?php
// auto-generated by sfPropelAdmin
// date: 2018/02/07 03:59:05
?>
<td colspan="4">
    <?php echo $wilayah->getWilayah() ?>
     - 
    <?php echo $wilayah->getKecamatan() ?>
     - 
    <?php echo $wilayah->getKelurahan() ?>
     - 
    <?php echo get_partial('opsi', array('type' => 'list', 'wilayah' => $wilayah)) ?>
     - 
</td>