<?php
// auto-generated by sfPropelAdmin
// date: 2018/01/23 09:43:08
?>
<ul class="sf_admin_actions">
  <li><?php echo button_to(__('Lihat Daftar'), 'ipalKomunal/list?id='.$ipal_komunal->getId(), array (
  'class' => 'sf_admin_action_list',
)) ?></li>
  <li><?php echo submit_tag(__('Simpan'), array (
  'name' => 'save_and_add',
  'class' => 'sf_admin_action_save_and_add',
)) ?></li>
  <li class="float-left"><?php if ($ipal_komunal->getId()): ?>
<?php echo button_to(__('Hapus Data'), 'ipalKomunal/deleteFlag?id='.$ipal_komunal->getId(), array (
  'confirm' => __('Hapus Data Ini ?\n('.$ipal_komunal->getNama().' - '.$ipal_komunal->getWilayah().')'),
  'class' => 'sf_admin_action_delete',
)) ?><?php endif; ?>
</li>
</ul>
