<?php
// auto-generated by sfPropelAdmin
// date: 2018/02/06 03:23:48
?>
<ul class="sf_admin_actions">
    <li><?php echo button_to(__('edit'), 'sfGuardUser/edit?id='.$sf_guard_user->getId(), array (
  'class' => 'sf_admin_action_edit',
)) ?></li>
</ul>
