<?php
// auto-generated by sfPropelAdmin
// date: 2018/01/23 05:11:12
?>
<ul class="sf_admin_actions">
  <li><?php echo button_to(__('Lihat Daftar'), 'bankSampah/list?id='.$bank_sampah->getId(), array (
  'class' => 'sf_admin_action_list',
)) ?></li>
  <li><?php echo submit_tag(__('Simpan'), array (
  'name' => 'save_and_add',
  'class' => 'sf_admin_action_save_and_add',
)) ?></li>
</ul>
