<?php
// auto-generated by sfPropelAdmin
// date: 2018/01/23 04:58:20
?>
<ul class="sf_admin_actions">
  <li><?php echo button_to(__('Lihat Daftar'), 'kader/list?id='.$kader->getId(), array (
  'class' => 'sf_admin_action_list',
)) ?></li>
  <li><?php echo submit_tag(__('Simpan'), array (
  'name' => 'save_and_add',
  'class' => 'sf_admin_action_save_and_add',
)) ?></li>
      <li class="float-left"><?php if ($kader->getId()): ?>
<?php echo button_to(__('Hapus Data'), 'kader/deleteFlag?id='.$kader->getId(), array (
  'confirm' => __('Hapus Data Ini ?\n('.$kader->getNama().' - '.$kader->getWilayah().')'),
  'class' => 'sf_admin_action_delete',
)) ?><?php endif; ?>
</li>

</ul>
