<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2018/02/05 04:29:49
sfConfig::add(array(
  'app_sf_guard_plugin_success_signin_url' => 'home',
  'app_sf_guard_plugin_success_signout_url' => 'home',
));
