<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2018/02/06 03:18:47
sfConfig::add(array(
  'mod_'.strtolower($moduleName).'_enabled' => true,
  'mod_'.strtolower($moduleName).'_view_class' => 'sfPHP',
  'mod_'.strtolower($moduleName).'_is_internal' => false,
));
