<?php
// auto-generated by sfPropelAdmin
// date: 2018/02/13 11:05:29
?>
<ul class="sf_admin_actions">
  <li><?php echo button_to(__('create'), 'bankSampah/create', array (
  'class' => 'sf_admin_action_create',
)) ?></li>
</ul>
