<?php
// auto-generated by sfPropelAdmin
// date: 2018/02/13 11:05:29
?>
<td colspan="12">
    <?php echo $bank_sampah->getWilayah() ?>
     - 
    <?php echo $bank_sampah->getNama() ?>
     - 
    <?php echo $bank_sampah->getAlamat() ?>
     - 
    <?php echo $bank_sampah->getDasarPendirian() ?>
     - 
    <?php echo get_partial('date', array('type' => 'list', 'bank_sampah' => $bank_sampah)) ?>
     - 
    <?php echo $bank_sampah->getSk() ?>
     - 
    <?php echo $bank_sampah->getKetua() ?>
     - 
    <?php echo $bank_sampah->getJumlahNasabah() ?>
     - 
    <?php echo get_partial('omset', array('type' => 'list', 'bank_sampah' => $bank_sampah)) ?>
     - 
    <?php echo get_partial('status_view', array('type' => 'list', 'bank_sampah' => $bank_sampah)) ?>
     - 
    <?php echo $bank_sampah->getKeterangan() ?>
     - 
    <?php echo get_partial('opsi', array('type' => 'list', 'bank_sampah' => $bank_sampah)) ?>
     - 
</td>