<?php
// auto-generated by sfPropelAdmin
// date: 2018/02/06 04:37:00
?>
<ul class="sf_admin_actions">
  <li><?php echo button_to(__('create'), 'ipalKomunal/create', array (
  'class' => 'sf_admin_action_create',
)) ?></li>
</ul>
